DELIMITER //
CREATE DEFINER=`root`@`localhost` FUNCTION `this_query`() RETURNS longtext CHARSET utf8
    READS SQL DATA
    DETERMINISTIC
    SQL SECURITY INVOKER
    COMMENT 'Return current query'
BEGIN
  return (SELECT INFO FROM INFORMATION_SCHEMA.PROCESSLIST WHERE ID = CONNECTION_ID());
END//
DELIMITER ;
